apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giroops
  name: giroops-2
spec:
  containers:
  - image: ngix
    name: giroops
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
